default_platform(:android)

platform :android do
  desc "Deploy MAUI Blazor app to internal testing track"
  lane :deploy do
    upload_to_play_store(
      track: ENV['PLAY_TRACK'], # Comes from GitHub Actions
      json_key: "fastlane/google-play-key.json",
      package_name: ENV['PACKAGE_NAME'],
      aab: "src/Witness/EMS.Witness/bin/Release/net8.0-android/publish/com.ems.witness.aab"
    )
  end
end
