default_platform(:android)

platform :android do
  desc "Deploy MAUI Blazor app to internal testing track"
  lane :deploy do
    upload_to_play_store(
      track: ENV['GitHub Action/Fastlane Deployment'], # Comes from GitHub Actions
      json_key: "fastlane/test-473707-u5-8f9daa805c8c.json",
      package_name: ENV['com.ems.witness'],
      aab: "/src/Witness/EMS.Witness/bin/Release/net8.0-android/publish/com.ems.witness.aab"
    )
  end
end