name: "[net8] Publish Witness Android"

on:
  workflow_dispatch:
env:
    SOURCE_PATH: src/Witness/EMS.Witness/

permissions:
  id-token: write   # Required for WIF
  contents: read

jobs:
  witness-publish-android:
    name: 🏗️ Build package
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Cache .NET workloads
        uses: actions/cache@v4
        with:
          path: ~/.dotnet
          key: ${{ runner.os }}-dotnet-maui-${{ hashFiles('**/*.csproj') }}
          
      - name: 💼 Install MAUI Workloads
        run: dotnet workload install maui --skip-manifest-update

      - name: 📦 Restore dependencies
        run: dotnet restore ${{ env.SOURCE_PATH }}

      - name: Build Android Release AAB
        run: dotnet publish src/Witness/EMS.Witness/EMS.Witness.csproj -f:net8.0-android -c:Release

  publish-to-google-play:
      name: 🚀 Upload to Google Play
      runs-on: windows-latest
      needs: witness-publish-android

      steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: 3.3  # or latest supported version
            bundler-cache: true

      - name: Install Fastlane    
        run: gem install fastlane -NV

      - name: Checkout code
        uses: actions/checkout@v4

      # Authenticate to Google using Workload Identity Federation
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/885247215557/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "play-deployer@test-473707-u5.iam.gserviceaccount.com"

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Export temporary JSON key for Fastlane
        run: |
          gcloud auth application-default print-access-token > token.txt
          gcloud auth application-default print-access-token --format=json > fastlane/google-play-key.json
          # (This file is ephemeral — valid only for this job)

      - name: Deploy to Google Play
        env:
          PLAY_TRACK: ${{ secrets.PLAY_TRACK }}
          PACKAGE_NAME: ${{ secrets.PACKAGE_NAME }}
        run: fastlane android deploy
