name: "[net8] Publish Witness Android"

on:
  workflow_dispatch:
env:
    SOURCE_PATH: src/Witness/EMS.Witness/
permissions:
  id-token: write   # Required for WIF
  contents: read

jobs:
  witness-publish-android:
    name: 🏗️ Build package
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Cache .NET workloads
        uses: actions/cache@v4
        with:
          path: |
            ~/.dotnet
            ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-maui-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-maui-
          
      - name: 💼 Install MAUI Android Workload
        run: dotnet workload install maui-android maui-ios --skip-manifest-update --skip-sign-check
        
      - name: 📦 Restore dependencies
        run: dotnet restore ${{ env.SOURCE_PATH }}

      - name: Remove old outputs
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force src\Witness\EMS.Witness\bin -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force src\Witness\EMS.Witness\obj -ErrorAction SilentlyContinue

      - name: Restore signing key
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "src/Witness/EMS.Witness/signing" | Out-Null
          $bytes = [System.Convert]::FromBase64String("${{ secrets.KEYSTORE_BASE64 }}")
          [IO.File]::WriteAllBytes("src/Witness/EMS.Witness/signing/ems-keystore.keystore", $bytes)

      - name: Build Android Release AAB
        shell: pwsh
        run: |
              dotnet publish src/Witness/EMS.Witness/EMS.Witness.csproj `
                -f:net8.0-android `
                -c:Release `
                -p:AndroidPackageFormat=aab `
                -p:AndroidKeyStore=true `
                -p:AndroidSigningKeyStore=signing/ems-keystore.keystore `
                -p:AndroidSigningStorePass=${{ secrets.KEYSTORE_PASSWORD }} `
                -p:AndroidSigningKeyAlias=${{ secrets.KEY_ALIAS }} `
                -p:AndroidSigningKeyPass=${{ secrets.KEYSTORE_PASSWORD }}

      - name: Decode AndroidManifest.xml
        shell: bash
        run: |
          echo "Decoding manifest from AAB..."
          aapt dump xmltree src/Witness/EMS.Witness/bin/Release/net8.0-android/publish/com.ems.witness-Signed.aab base/manifest/AndroidManifest.xml > manifest_decoded.txt
          cat manifest_decoded.txt
              
      - name: 📤 Upload AAB as artifact
        uses: actions/upload-artifact@v4
        with:
          name: witness-aab
          path: src/Witness/EMS.Witness/bin/Release/net8.0-android/publish/com.ems.witness-Signed.aab

  publish-to-google-play:
      name: 🚀 Upload to Google Play
      runs-on: windows-latest
      needs: witness-publish-android

      steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: 3.3  # or latest supported version
            bundler-cache: true

      - name: Install Fastlane    
        run: gem install fastlane -NV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write Google Play key
        shell: pwsh
        run: |
          Set-Content -Path "fastlane/google-play-key.json" -Value '${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}'
   
      - name: 📥 Download built AAB
        uses: actions/download-artifact@v4
        with:
          name: witness-aab
          path: src/Witness/EMS.Witness/bin/Release/net8.0-android/publish

      - name: Deploy to Google Play
        env:
          PLAY_TRACK: ${{ vars.PLAY_TRACK }}
          PACKAGE_NAME: ${{ vars.PACKAGE_NAME }}
        run: fastlane android deploy
